export const A_FormatYMultiPageInputOptions: MultiPageMockupInputOptions = {
  mockupBackgroundFill: '#fff',
  dayCellHeight: 7.55,
  dayCellWidth: 13.5,
  calendarGridX: 5,
  calendarGridY: 96,
  daysFontSize: 4.25,
  imagePlaceholderWidth: 95,
  imagePlaceholderHeight: 78,
  imagePlaceholderX: 5,
  imagePlaceholderY: 5,
  dayCellStyles: 'fill: none; stroke:#999999; stroke-miterlimit: 10; stroke-width: 0.15%;',
  monthTitleX: 15,
  monthTitleY: 90,
  monthTitleFontSize: 7,
  yearTitleX: 70.4,
  yearTitleY: 90,
  yearTitleFontSize: 7,
  weekDayY: -1,
  weekDayFontSize: 1.6,
  weekDaysY: 95,
};

export const A_FormatXMultiPageInputOptions: MultiPageMockupInputOptions = {
  mockupBackgroundFill: '#fff',
  dayCellHeight: 7.55,
  dayCellWidth: 9.7,
  calendarGridX: 77,
  calendarGridY: 38,
  daysFontSize: 3.8,
  imagePlaceholderWidth: 70,
  imagePlaceholderHeight: 95,
  imagePlaceholderX: 5,
  imagePlaceholderY: 5,
  dayCellStyles: 'fill: none; stroke:#999999; stroke-miterlimit: 10; stroke-width: 0.15%;',
  monthTitleX: 82,
  monthTitleY: 30,
  monthTitleFontSize: 7,
  yearTitleX: 126,
  yearTitleY: 30,
  yearTitleFontSize: 7,
  weekDayY: 0,
  weekDayFontSize: 1.6,
  weekDaysY: 35,
};
