export const A_FormatYSinglePageInputOptions: SinglePageMockupInputOptions = {
  mockupBackgroundFill: '#fff',
  dayCellHeight: 2.23,
  dayCellWidth: 3.3,
  calendarGridX: 0,
  calendarGridY: 4.35,
  daysFontSize: 1.7,
  monthCellHeight: 19,
  monthCellWidth: 23,
  monthCellPadding: 1.25,
  imagePlaceholderWidth: 95,
  imagePlaceholderHeight: 78,
  imagePlaceholderX: 5,
  imagePlaceholderY: 5,
  calendarGridLeftIndent: 5,
  calendarGridTopIndent: 65,
  dayCellStyles: 'fill: none;stroke: none; stroke-width: 0; stroke-miterlimit: 0;',
  monthTitleX: 2.5,
  monthTitleY: 1.8,
  monthTitleFontSize: 2,
  yearTitleX: 16.5,
  yearTitleY: 1.8,
  yearTitleFontSize: 2,
  weekDayY: 3.33,
  weekDayFontSize: 1.5,
  descenderException: 3.2,
  numberOfColumns: 4,
};

export const A_FormatXSinglePageInputOptions: SinglePageMockupInputOptions = {
  mockupBackgroundFill: '#fff',
  dayCellHeight: 1.75,
  dayCellWidth: 2.8,
  calendarGridX: 0,
  calendarGridY: 4.35,
  daysFontSize: 1.4,
  monthCellHeight: 14.83,
  monthCellWidth: 19,
  monthCellPadding: 1.35,
  imagePlaceholderWidth: 95,
  imagePlaceholderHeight: 95,
  imagePlaceholderX: 5,
  imagePlaceholderY: 5,
  calendarGridLeftIndent: 104,
  calendarGridTopIndent: -11.75,
  dayCellStyles: 'fill: none;stroke: none; stroke-width: 0; stroke-miterlimit: 0;',
  monthTitleX: 2.5,
  monthTitleY: 1.8,
  monthTitleFontSize: 2,
  yearTitleX: 12.5,
  yearTitleY: 1.8,
  yearTitleFontSize: 2,
  weekDayY: 3.33,
  weekDayFontSize: 1.4,
  descenderException: 3.2,
  numberOfColumns: 2,
};
